const ROUTES = {
  Splash: 'Splash',
  WalkThrough: 'WalkThrough',
  SignIn: 'SingIn',
  SignUp: 'SignUp',
  ForgotPassword: 'ForgotPassword',
  VerifyEmail: 'VerifyEmail',
  VerifyMobile: 'VerifyMobile',
  ResetPassword: 'ResetPassword',
  ResetPasswordSuccess: 'ResetPasswordSuccess',
  CreatAccount: 'CreatAccount',
  FullName: 'FullName',
  Gender: 'Gender',
  BirthDay: 'BirthDay',
  Blood: 'Blood',
  Weight: 'Weight',
  Height: 'Height',
  MainPage: 'MainPage',
  PricePlan: 'PricePlan',
  Menu: 'Menu',
  Services: 'Services',
  DashBoard: 'DashBoard',
  DailyReport: 'Daily Report',
  GlucoseLevel: 'Glucose Level',
  HeartRate: 'Heart Rate',
  Profile: 'Profile',
  FoodProfile: 'Food Profile',
  FoodDetails: 'Food Details',
  Finger: 'Finger',
  NewsHealthy: 'NewsHealthy',
  Notification: 'Notification',
  UpComing: 'UpComing',
  Past: 'Past',
  AppointmentList: 'AppointmentList',
  AppointmentListTab: 'AppointmentListTab',
  AppointmentCalendar: 'AppointmentCalendar',
  CreateAppointment: 'CreateAppointment',
  AppointmentDetails: 'AppointmentDetails',
  FindDoctors: 'FindDoctors',
  FindHospital: 'FindHospital',
  ResultFindDoctor: 'Result Find Doctor',
  StaticsHealth: 'StaticsHealth',
  Day: 'Day',
  Week: 'Week',
  Month: 'Month',
  Year: 'Year',
  IndicatorsSettings: 'IndicatorsSettings',
  IndicatorsSettingsTab: 'IndicatorsSettingsTab',
  Devices: 'Devices',
  Indicator: 'Indicator',
  InputTestIndicators: 'InputTestIndicators',
  SetGoal: 'SetGoal',
  GoalSettings: 'GoalSettings',
  Doctors: 'Doctors',
  DoctorsTab: 'DoctorsTab',
  Nearby: 'Nearby',
  ListAll: 'ListAll',
  Favorites: 'Favorites',
  MapsDoctors: 'MapsDoctors',
  DoctorProfile: 'DoctorProfile',
  DoctorInformation: 'DoctorInformation',
  DoctorAddress: 'DoctorAddress',
  DoctorReview: 'DoctorReview',
  DoctorMessage: 'DoctorMessage',
  CallDoctor: 'CallDoctor',
  VideoCall: 'VideoCall',
  UserProfile: 'UserProfile',
  Insurance: 'Insurance ',
  BookAppointment: 'BookAppointment',
  Drugs: 'Drugs',
  ListDrugs: 'ListDrugs',
  AddDrugs: 'AddDrugs',
  DrugDetails: 'DrugsDetails',
  DrugShop: 'DrugsShop',
  DrugShopDetails: 'DrugsShopDetails',
  Cart: 'Cart',
  Billing: 'Billing',
  NewsTab: 'NewsTab',
  News: 'News',
  Explorer: 'Explorer',
  Trends: 'Trends',
  Follow: 'Follow',
  NewsBookmark: 'NewsBookmark',
  NewsDetails: 'NewsDetails',
  NewsComment: 'NewsComment',
  MainBottomTab: 'MainBottomTab',
  MainBottomStack: 'MainBottomStack',
  Drawer: 'Drawer',
  DrawerStack: 'DrawerStack',
};
export default ROUTES;
